### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Samirbhajipale**

### CODE REVIEW

**Comment by FFY00** [comment]
@DiogoMRSilva this is spam trying to get entries for https://hacktoberfest.digitalocean.com/.

It's unfortunate that initiatives like this, which should motivate people to do open source, are met with this kind of behavior.

Please label it as `invalid` so that it does not count towards their hacktoberfest PR count.

**Comment by renancaraujo** [comment]
Tudo por uma tshirt

**Comment by FFY00** [comment]
Pois é :confused:

**Comment by FFY00** [comment]
Infelizmente não dá. O Github permite bloquear o repositório a contribuidores mas isso é apenas temporário e só dura 24h.

**Pull request closed without merging**
